### ISSUE TITLE
Translation into Portuguese of Portugal

### ISSUE THREAD

**Issue by MiguelRenato** [Zavy86/WikiDocs#124]
### Describe the feature

Hello, here is the translation into Portuguese

[pt-pt.json](https://github.com/Zavy86/WikiDocs/files/15298374/pt-pt.json)

best regards
Miguel

### Extra fields

- [ ] I'd like to work on this feature

**Comment by Zavy86** [comment]
hi Miguel, if you want you can create a pull request.. you will compare as a contributor! it's easy!

**Comment by ffiesta** [comment]
Hello, some translations are in portugues off Brasil, like example:

English version:
`Payoff": "Just a databaseless markdown flat-file wiki engine..",`  

In uploaded file version
`"Payoff": "Apenas um mecanismo wiki de arquivo simples com markdown sem banco de dados.",`  \< -- This is translated by google and this have portugues/brasil in midle os portuguese/portuguese.

> In portugues we don't say `banco de dados` we say `base de dados` 

 Even though I am Portuguese, as in Portugal we can interpret it in different ways, I have had some difficulty translating it, as it doesn't sound good, and some words in english don't have direct conversion like wiki.

In direct translation maybe we can say
`"Payoff": "Apenas um arquivo simples  markdown, sem base de dados." Or perhaps "Apenas um simples arquivo markdown sem base de dados." Or perhaps "Um arquivo simples em markdown sem base de dados"` 

And i can find some more translations,  

\.... because this it take more time that I wan't.

I will update this, when i translate and ask to some friends a review, to make some sense.
