### ISSUE TITLE
Show images while editig

### ISSUE THREAD

**Issue by mhbacks** [Zavy86/WikiDocs#153]
### Describe the feature

When a Image is added to the editing textblock, it is replaced with the normal MD Image insert tag. It would be really cool, when you can see the image there directly. It is not so easy to describe the pasted screenshot, when you cant see it anymore

thank you for your work! I like wididocs really much!

### Extra fields

- [ ] I'd like to work on this feature

**Comment by ffiesta** [comment]
Hi,

You can view images and MD files if you select the **Toggle Side by Side F9** om menu bar, inside of **Edit document** 
![image](https://github.com/user-attachments/assets/103dc8f7-1719-4eb3-8c77-9a087e532f75)

I normaly edit and create a few documens in Android Chrome / Brave Browser, and because it's simple and doesn't have your requested function, I can work on smartphone.

![image](https://github.com/user-attachments/assets/749a3c6f-70ba-4092-bd76-6a6ae272dae2)

![image](https://github.com/user-attachments/assets/f1d78ff3-57c7-4c8f-b026-f07043542e87)

**Comment by mhbacks** [comment]
Hi ffiesta,
thank you, that is much better than show it inline!
best regards,
Max
