### ISSUE TITLE
nginx config file

### ISSUE THREAD

**Issue by youmakemyday** [Zavy86/WikiDocs#22]
Hello und a big thanks for this great wiki!

A have a small Test-Installation on apache2, that works perfect. My Main-Installation should run on nginx but i have problems with the rewrite rule. Can you help?

$ nano /etc/nginx/sites-available/wiki
```
....
        location  / {
             index index.php;
             try_files $uri $uri/ =404;
                  if (!-f $request_filename){
                        set $rule_0 1;
                  }
                  if ($rule_0 = "1"){
                        rewrite ^/(.*)$ /index.php?doc=$1 last;
                  }
        }
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/run/php/php8.0-fpm.sock;
        }
}
```

**Comment by Zavy86** [comment]
Hi, I don't use nginx and I have no experience with it to help you.
You could try to see this article:
https://www.nginx.com/blog/converting-apache-to-nginx-rewrite-rules/
If you can solve the problem, I would ask you to share your solution in order to integrate it into the repository.
Thank you and good luck! :)

**Comment by youmakemyday** [comment]
Thx for your response ... this is working with nginx:

`        location /wikidocs/ {
                if (!-e $request_filename){
                rewrite ^/(.*)$ /index.php?doc=$1 last;
                }
                try_files $uri $uri/ =404;
        }`
