### ISSUE TITLE
Pages will not delete

### ISSUE THREAD

**Issue by superhu4** [Zavy86/WikiDocs#25]
Despite receiving a notification that a page has been deleted, the page will not delete.

**Comment by pool-alpin** [comment]
Hi, I have the same problem, using the docker image with my User/Group ID set in the compose file.
There is no difference when using volumes or bind mounts.

**Comment by Zavy86** [comment]
@reyemxela can you try on Docker please when you have a moment please?

**Comment by reyemxela** [comment]
I did actually notice this the other day myself. After messing around with it a bit just now, it's erroring out on the `rename("/path/documents/origfile","/path/trash/file_1234")` line.

I think that's happening on the docker version because the documents folder is technically a separate volume than the rest of the folder structure, and rename doesn't like to move things across volumes. But the issue does seem to also happen on the demo site, which I don't believe is running the docker version?

Either way, not sure what a good fix for this would be. Would it make sense to have the "trash" directory be under the documents directory, and just ignored? Then as a side effect your trash is also being backed up wherever your documents are (which might be good or bad), similar to the versions folders.

**Comment by Zavy86** [comment]
Can you try if it works for you with the latest version?
I think it was a problem due to the subdirectories now I have renamed the slash...

```
$trash_id=str_replace('/','___',$DOC->ID)."_".date("Ymd_His");
if(is_dir($DOC->DIR)){rename($DOC->DIR,DIR."trash/".$trash_id);}
```

#@reyemxela @superhu4

**Comment by Zavy86** [comment]
@reyemxela is perhaps necessary to add a link to the trash directory in the docker configuration?

https://wikidocs.it/documentation/setup

**Comment by Zavy86** [comment]
Fixed
