### ISSUE TITLE
javascript error on save

### ISSUE THREAD

**Issue by howardlesshippin** [Zavy86/WikiDocs#42]
Hi - I have just installed WikiDocs on my VPS
The installation was easy (though the automatic configuration script did not work).
I would have liked a better explanation of what to do regarding the generation of an MD5 hashed password, but I figured it out (and found a website that provides a hashing service). (The hash goes in the back end, the password itself in the front end, for anyone as stupid as me.)
Anyway, after logging in, and trying to edit the title, a javascript dialogue box pops up about every second with "draft_saving_error".
This happens in Firefox and Vivaldi.
My server is running PHP 8.2.
Thanks

**Comment by Zavy86** [comment]
Hi @howardlesshippin, it could be a permissions problem, can you verify that the apache user has write permissions on the site directories?

**Comment by Zavy86** [comment]
@howardlesshippin did you solve the problem?

**Comment by howardlesshippin** [comment]
Sorry for not responding and thanks for your own response. I will let you know in a few days as I am away. Your solution is likely true though because I did not adjust the permissions.

--
Howard Shippin
web: howard.shippins.net
fedi: ***@***.***

**Comment by Zavy86** [comment]
ok i wait your news

**Comment by howardlshippin** [comment]
Thanks Zavy86.  That was it.  All is working fine now.  For others facing the same difficulty: on my ubuntu vpn server, I followed the directions at https://www.internalpointers.com/post/right-folder-permission-website in order to give the correct permissions to the webserver.  For the last step mentioned there, I added an -R to the command (that may have been necessary).
